// <auto-generated />
using System;
using Food.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Food.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    [Migration("20260808164439_AddFavoriteMeals")]
    partial class AddFavoriteMeals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Food.Domain.Ingredients.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Food.Domain.Logging.FavoriteMeal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("favorite_meals", null, t =>
                        {
                            t.HasCheckConstraint("CK_favorite_meals_exactly_one_source", "(\"RecipeId\" IS NOT NULL) <> (\"IngredientId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Food.Domain.Logging.MealLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MealSlot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LogDate");

                    b.ToTable("meal_logs", null, t =>
                        {
                            t.HasCheckConstraint("CK_meal_logs_exactly_one_source", "(\"RecipeId\" IS NOT NULL) <> (\"IngredientId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Food.Domain.Nutrition.NutritionTarget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EffectiveFrom");

                    b.ToTable("nutrition_targets", (string)null);
                });

            modelBuilder.Entity("Food.Domain.Recipes.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Food.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IngredientId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("Food.Domain.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Food.Domain.Users.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("numeric");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Food.Domain.Ingredients.Ingredient", b =>
                {
                    b.OwnsOne("Food.Domain.Common.MacroBreakdown", "MacrosPer100g", b1 =>
                        {
                            b1.Property<long>("IngredientId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Calories")
                                .HasColumnType("numeric")
                                .HasColumnName("calories_per_100g");

                            b1.Property<decimal>("CarbsG")
                                .HasColumnType("numeric")
                                .HasColumnName("carbs_per_100g");

                            b1.Property<decimal>("FatG")
                                .HasColumnType("numeric")
                                .HasColumnName("fat_per_100g");

                            b1.Property<decimal>("FiberG")
                                .HasColumnType("numeric")
                                .HasColumnName("fiber_per_100g");

                            b1.Property<decimal>("ProteinG")
                                .HasColumnType("numeric")
                                .HasColumnName("protein_per_100g");

                            b1.HasKey("IngredientId");

                            b1.ToTable("ingredients");

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.OwnsMany("Food.Domain.Ingredients.IngredientTag", "Tags", b1 =>
                        {
                            b1.Property<long>("IngredientId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("IngredientId", "Name");

                            b1.ToTable("ingredient_tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.Navigation("MacrosPer100g")
                        .IsRequired();

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Food.Domain.Logging.FavoriteMeal", b =>
                {
                    b.OwnsOne("Food.Domain.Logging.LoggableItem", "Item", b1 =>
                        {
                            b1.Property<long>("FavoriteMealId")
                                .HasColumnType("bigint");

                            b1.Property<long?>("IngredientId")
                                .HasColumnType("bigint")
                                .HasColumnName("IngredientId");

                            b1.Property<long?>("RecipeId")
                                .HasColumnType("bigint")
                                .HasColumnName("RecipeId");

                            b1.Property<decimal?>("ServingsCount")
                                .HasColumnType("numeric")
                                .HasColumnName("ServingsCount");

                            b1.HasKey("FavoriteMealId");

                            b1.HasIndex("IngredientId");

                            b1.HasIndex("RecipeId");

                            b1.ToTable("favorite_meals");

                            b1.WithOwner()
                                .HasForeignKey("FavoriteMealId");

                            b1.HasOne("Food.Domain.Ingredients.Ingredient", "Ingredient")
                                .WithMany()
                                .HasForeignKey("IngredientId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Food.Domain.Recipes.Recipe", "Recipe")
                                .WithMany()
                                .HasForeignKey("RecipeId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.OwnsOne("Food.Domain.Common.Quantity", "Quantity", b2 =>
                                {
                                    b2.Property<long>("LoggableItemFavoriteMealId")
                                        .HasColumnType("bigint");

                                    b2.Property<decimal>("Grams")
                                        .HasColumnType("numeric")
                                        .HasColumnName("quantity_g");

                                    b2.HasKey("LoggableItemFavoriteMealId");

                                    b2.ToTable("favorite_meals");

                                    b2.WithOwner()
                                        .HasForeignKey("LoggableItemFavoriteMealId");
                                });

                            b1.Navigation("Ingredient");

                            b1.Navigation("Quantity");

                            b1.Navigation("Recipe");
                        });

                    b.Navigation("Item")
                        .IsRequired();
                });

            modelBuilder.Entity("Food.Domain.Logging.MealLog", b =>
                {
                    b.OwnsOne("Food.Domain.Logging.LoggableItem", "Item", b1 =>
                        {
                            b1.Property<long>("MealLogId")
                                .HasColumnType("bigint");

                            b1.Property<long?>("IngredientId")
                                .HasColumnType("bigint")
                                .HasColumnName("IngredientId");

                            b1.Property<long?>("RecipeId")
                                .HasColumnType("bigint")
                                .HasColumnName("RecipeId");

                            b1.Property<decimal?>("ServingsCount")
                                .HasColumnType("numeric")
                                .HasColumnName("ServingsCount");

                            b1.HasKey("MealLogId");

                            b1.HasIndex("IngredientId");

                            b1.HasIndex("RecipeId");

                            b1.ToTable("meal_logs");

                            b1.HasOne("Food.Domain.Ingredients.Ingredient", "Ingredient")
                                .WithMany()
                                .HasForeignKey("IngredientId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.WithOwner()
                                .HasForeignKey("MealLogId");

                            b1.HasOne("Food.Domain.Recipes.Recipe", "Recipe")
                                .WithMany()
                                .HasForeignKey("RecipeId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.OwnsOne("Food.Domain.Common.Quantity", "Quantity", b2 =>
                                {
                                    b2.Property<long>("LoggableItemMealLogId")
                                        .HasColumnType("bigint");

                                    b2.Property<decimal>("Grams")
                                        .HasColumnType("numeric")
                                        .HasColumnName("quantity_g");

                                    b2.HasKey("LoggableItemMealLogId");

                                    b2.ToTable("meal_logs");

                                    b2.WithOwner()
                                        .HasForeignKey("LoggableItemMealLogId");
                                });

                            b1.Navigation("Ingredient");

                            b1.Navigation("Quantity");

                            b1.Navigation("Recipe");
                        });

                    b.Navigation("Item")
                        .IsRequired();
                });

            modelBuilder.Entity("Food.Domain.Nutrition.NutritionTarget", b =>
                {
                    b.OwnsOne("Food.Domain.Common.MacroBreakdown", "Macros", b1 =>
                        {
                            b1.Property<long>("NutritionTargetId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Calories")
                                .HasColumnType("numeric")
                                .HasColumnName("calories_kcal");

                            b1.Property<decimal>("CarbsG")
                                .HasColumnType("numeric")
                                .HasColumnName("carbs_g");

                            b1.Property<decimal>("FatG")
                                .HasColumnType("numeric")
                                .HasColumnName("fat_g");

                            b1.Property<decimal>("FiberG")
                                .HasColumnType("numeric")
                                .HasColumnName("fiber_g");

                            b1.Property<decimal>("ProteinG")
                                .HasColumnType("numeric")
                                .HasColumnName("protein_g");

                            b1.HasKey("NutritionTargetId");

                            b1.ToTable("nutrition_targets");

                            b1.WithOwner()
                                .HasForeignKey("NutritionTargetId");
                        });

                    b.Navigation("Macros")
                        .IsRequired();
                });

            modelBuilder.Entity("Food.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.HasOne("Food.Domain.Ingredients.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Food.Domain.Recipes.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Food.Domain.Common.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<long>("RecipeIngredientId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Grams")
                                .HasColumnType("numeric")
                                .HasColumnName("quantity_g");

                            b1.HasKey("RecipeIngredientId");

                            b1.ToTable("recipe_ingredients");

                            b1.WithOwner()
                                .HasForeignKey("RecipeIngredientId");
                        });

                    b.Navigation("Ingredient");

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("Food.Domain.Recipes.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
