// <auto-generated />
using System;
using Food.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Food.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    partial class FoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Food.Domain.Ingredients.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Food.Domain.Ingredients.Ingredient", b =>
                {
                    b.OwnsOne("Food.Domain.Common.MacroBreakdown", "MacrosPer100g", b1 =>
                        {
                            b1.Property<long>("IngredientId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Calories")
                                .HasColumnType("numeric")
                                .HasColumnName("calories_per_100g");

                            b1.Property<decimal>("CarbsG")
                                .HasColumnType("numeric")
                                .HasColumnName("carbs_per_100g");

                            b1.Property<decimal>("FatG")
                                .HasColumnType("numeric")
                                .HasColumnName("fat_per_100g");

                            b1.Property<decimal>("FiberG")
                                .HasColumnType("numeric")
                                .HasColumnName("fiber_per_100g");

                            b1.Property<decimal>("ProteinG")
                                .HasColumnType("numeric")
                                .HasColumnName("protein_per_100g");

                            b1.HasKey("IngredientId");

                            b1.ToTable("ingredients");

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.OwnsMany("Food.Domain.Ingredients.IngredientTag", "Tags", b1 =>
                        {
                            b1.Property<long>("IngredientId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("IngredientId", "Name");

                            b1.ToTable("ingredient_tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.Navigation("MacrosPer100g")
                        .IsRequired();

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
