<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Food.Application\Food.Application.csproj" />
    <ProjectReference Include="..\Food.Domain\Food.Domain.csproj" />
    <ProjectReference Include="..\Food.Shared\Food.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
